name: Build and Release Executables

on:
  # 手动触发工作流
  workflow_dispatch:

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile fix_replay.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fix_replay-windows
          path: dist/fix_replay.exe

  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile fix_replay.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fix_replay-linux
          path: dist/fix_replay

  build-macos:
    name: Build for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile fix_replay.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fix_replay-macos
          path: dist/fix_replay

  release:
    name: Create GitHub Release
    needs:
      - build-windows
      - build-linux
      - build-macos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: fix_replay-windows
          path: ./artifacts/windows

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: fix_replay-linux
          path: ./artifacts/linux

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: fix_replay-macos
          path: ./artifacts/macos

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
          release_name: "fix_replay v1.0.0"
          body: |
            自动生成的发布版本：
            - Windows
            - Linux
            - macOS
          draft: false
          prerelease: false
          files: |
            ./artifacts/windows/fix_replay.exe
            ./artifacts/linux/fix_replay
            ./artifacts/macos/fix_replay
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
