name: Build and Release Executables

on:
  # 手动触发工作流
  workflow_dispatch:

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile fix_replay.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: fix_replay-windows
          path: dist/fix_replay.exe

  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile fix_replay.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: fix_replay-linux
          path: dist/fix_replay

  build-macos:
    name: Build for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile fix_replay.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: fix_replay-macos
          path: dist/fix_replay

  release:
    name: Create GitHub Release
    needs:
      - build-windows
      - build-linux
      - build-macos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: fix_replay-windows
          path: ./artifacts/windows

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: fix_replay-linux
          path: ./artifacts/linux

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: fix_replay-macos
          path: ./artifacts/macos

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0
          release_name: "fix_replay v1.0.0"
          body: |
            自动生成的发布版本：
            - Windows
            - Linux
            - macOS
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows executable
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/windows/fix_replay.exe
          asset_name: fix_replay-windows.exe
          asset_content_type: application/octet-stream

      - name: Upload Linux executable
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/linux/fix_replay
          asset_name: fix_replay-linux
          asset_content_type: application/octet-stream

      - name: Upload macOS executable
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/macos/fix_replay
          asset_name: fix_replay-macos
          asset_content_type: application/octet-stream
